### PR TITLE
refact: adopt & use apache version in toolchain (#353)

### PR DESCRIPTION
**Pull request by imbajin**
**This PR should review and merge first (highest priority) to enable the CI test in each module**

And the import format will be unified together in next PR based on branch `client-rename`

### CODE REVIEW

**Review by javeme — APPROVED** [review]

**Comment by imbajin** [comment]
image

the root case is we import 2 `jersey` dependencies, so meet the conflicts

image

Tips: if we find a jar import with 2 version, we could use `maven dependency analyzer` to find the conflicts quickly, and exclude it

**Comment by imbajin** [comment]
image

2.12 scala need jackthon <2.13

**Comment by simon824** [comment]
You can run `hugegraph-dist/scripts/dependency/regenerate_known_dependencies.sh` locally to generate the latest `konw-dependencies.txt` file. `Licenses` can be added together later.

**Comment by imbajin** [comment]
Due to the dependencies is not stable now, ignore the 3rd dep check, and fix them when all code stable

**Review by coderzc — APPROVED** [review]

**Review by zyxxoo — APPROVED** [review]

**Pull request merged**
