### PR TITLE
chore: remove apache stage repo & update mail rule

### PR DESCRIPTION
**Pull request by z7658329**
follow https://github.com/apache/incubator-hugegraph/pull/2128#issuecomment-1469844210

### CODE REVIEW

**Comment by imbajin** [comment]
@wanganjuan seems the fe building is broken, could u help to check it?
image

**Comment by wanganjuan** [comment]
> @wanganjuan seems the fe building is broken, could u help to check it? image

What is the version of nodejs ？ you can use 'node -v'

**Comment by imbajin** [comment]
> > @wanganjuan seems the fe building is broken, could u help to check it? image
> 
> What is the version of nodejs ？ you can use 'node -v'

check the details in the [ci log](https://github.com/apache/incubator-hugegraph-toolchain/actions/runs/4274694861/jobs/7441496525), seems version is v18.xx.xx

**Comment by wanganjuan** [comment]
> > What is the version of nodejs ？ you can use 'node -v'
> 
> check the details in the [ci log](https://github.com/apache/incubator-hugegraph-toolchain/actions/runs/4274694861/jobs/7441496525), seems version is v18.xx.xx

can you  uninstall Node.js version 18.xx.xx and reinstall Node.js version 16+

**Comment by imbajin** [comment]
> > > What is the version of nodejs ？ you can use 'node -v'
> > 
> > 
> > check the details in the [ci log](https://github.com/apache/incubator-hugegraph-toolchain/actions/runs/4274694861/jobs/7441496525), seems version is v18.xx.xx
> 
> can you uninstall Node.js version 18.xx.xx and reinstall Node.js version 16+

maybe we should check the github action rule to specify it?

**Review by imbajin — APPROVED** [review]

**Review by javeme — APPROVED** [review]

**Pull request merged**
