### PR TITLE
doc: fix build status badge link

### PR DESCRIPTION
**Pull request by liuxiaocs7**
as title

before
Snipaste_2023-05-07_19-04-19

after
Snipaste_2023-05-07_19-05-49

### CODE REVIEW

**Review by imbajin — COMMENTED** [review]
Thanks，could u please also check/update the link in client module？

Add feel free to add some new links if u find some nice ico in other repo（😁）

**Comment by liuxiaocs7** [comment]
Hi, @imbajin, thanks for your comments, the link in client module fixed now.

The （pink） code-coverage link seem work fine, could you point out what is wrong?

image

**Comment by liuxiaocs7** [comment]
> Add feel free to add some new links if u find some nice ico in other repo😁

Good idea, i'll keep an eye out :)

**Comment by imbajin** [comment]
> Hi, @imbajin, thanks for your comments, the link in client module fixed now.
> 
> The （pink） code-coverage link seem work fine, could you point out what is wrong?
> 
> image
> 

in homepage（unknown），seems use client or remove it

**Comment by liuxiaocs7** [comment]
> > Hi, @imbajin, thanks for your comments, the link in client module fixed now.
> > The （pink） code-coverage link seem work fine, could you point out what is wrong?
> > image
> 
> in homepage（unknown），seems use client or remove it
> 
> 

According the website: https://app.codecov.io/gh/hugegraph, there is no uploaded codecov statistics for toolchain, so i'll remove this in homepage.

**Review by imbajin — APPROVED** [review]

**Review by JackyYangPassion — APPROVED** [review]

**Pull request merged**
